# Generated by Django 5.0.3 on 2024-03-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20240311_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.TextField(default='nill'),
        ),
    ]
