# Generated by Django 5.0.3 on 2024-03-11 14:43

from django.db import migrations

def create_employee_statuses(apps, schema_editor):
    Employee = apps.get_model('api', 'Employee')
    EmployeeStatus = apps.get_model('api', 'EmployeeStatus')
    for employee in Employee.objects.all():
        EmployeeStatus.objects.create(employee=employee, is_online=False)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_employee_name'),
    ]

    operations = [
        migrations.RunPython(create_employee_statuses),
    ]
