# Generated by Django 5.0.3 on 2024-03-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20240311_2131'),
    ]

    operations = [
    ]
