# Generated by Django 5.0.3 on 2024-03-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_employeestatus_employee_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeStatus',
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='1234', max_length=255),
        ),
    ]
