# Generated by Django 5.0.3 on 2024-03-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_employeestatus_employee_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Unassigned'), (1, 'Assigned to a PC but not accepted'), (2, 'Assigned to a FR but not accepted'), (3, 'Assigned to a FR and accepted'), (4, 'Completed')], default=0)),
                ('coordinator', models.CharField(blank=True, max_length=255, null=True)),
                ('freelancer', models.CharField(blank=True, max_length=255, null=True)),
                ('repo_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
