# Generated by Django 5.0.4 on 2024-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_employee_spreadsheet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='coordinator',
            new_name='accepted_coordinator',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='freelancer',
            new_name='final_fr',
        ),
        migrations.RenameField(
            model_name='enquiry',
            old_name='repo_link',
            new_name='wp_link',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='description',
        ),
        migrations.RemoveField(
            model_name='enquiry',
            name='status',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='resolve_status',
            field=models.CharField(choices=[('TIME_ISSUES', 'Time Issues'), ('DISTANCE_ISSUES', 'Distance Issues'), ('PAYMENT_PENDING', 'Payment Pending'), ('ORDER_PLACED', 'Order Complete'), ('NO_RESPONSE', 'No Response'), ('SERVICES_NOT_AVAILABLE', 'Services Not Available'), ('RESOLVED', 'Resolved')], max_length=255, null=True),
        ),
    ]
